version: '3'
services:
  web:
    build: .
    container_name: gnpscytoscape
    ports:
    - "5051:5051"
    volumes:
    - ./static:/app/static
    depends_on: 
      - redis
  worker1:
    build: .
    container_name: gnpscytoscape_worker1
    volumes:
    - ./static:/app/static
    command: /app/run_celery_worker.sh
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 5000M
    depends_on: 
      - redis
  worker2:
    build: .
    container_name: gnpscytoscape_worker2
    volumes:
    - ./static:/app/static
    command: /app/run_celery_worker.sh
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 5000M
    depends_on: 
      - redis
  worker3:
    build: .
    container_name: gnpscytoscape_worker3
    volumes:
    - ./static:/app/static
    command: /app/run_celery_worker.sh
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 5000M
    depends_on: 
      - redis
  redis:
    image: redis