version: '3'
services:
  cytoscape-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: cytoscape.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: cytoscape.gnps2.org
      LETSENCRYPT_EMAIL: miw023@ucsd.edu

networks:
  nginx-net:
    external:
      name: nginx-net