version: '3'
services:
  cytoscape-web:
    build: .
    container_name: gnpscytoscape
    ports:
    - "5051:5000"
    volumes:
    - ./static:/app/static
    command: /app/run_server.sh
    depends_on: 
      - cytoscape-redis
    networks:
      - default
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8000M
  
  cytoscape-worker1:
    build: .
    container_name: gnpscytoscape_worker1
    volumes:
    - ./static:/app/static
    command: /app/run_celery_worker.sh
    restart: unless-stopped
    depends_on: 
      - cytoscape-redis
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 16000M
  
  cytoscape-redis:
    image: redis
    networks:
      - default
    restart: unless-stopped